#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DataSource")]
public partial class Careers_listDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void Insertcareers_list(careers_list instance);
  partial void Updatecareers_list(careers_list instance);
  partial void Deletecareers_list(careers_list instance);
  #endregion
	
	public Careers_listDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DB_69755_aspclassConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public Careers_listDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public Careers_listDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public Careers_listDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public Careers_listDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<careers_list> careers_list
	{
		get
		{
			return this.GetTable<careers_list>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.careers_list")]
public partial class careers_list : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private string _job_title;
	
	private string _job_type;
	
	private string _job_description;
	
	private string _requirements;
	
	private System.DateTime _publish_date;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void Onjob_titleChanging(string value);
    partial void Onjob_titleChanged();
    partial void Onjob_typeChanging(string value);
    partial void Onjob_typeChanged();
    partial void Onjob_descriptionChanging(string value);
    partial void Onjob_descriptionChanged();
    partial void OnrequirementsChanging(string value);
    partial void OnrequirementsChanged();
    partial void Onpublish_dateChanging(System.DateTime value);
    partial void Onpublish_dateChanged();
    #endregion
	
	public careers_list()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_job_title", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string job_title
	{
		get
		{
			return this._job_title;
		}
		set
		{
			if ((this._job_title != value))
			{
				this.Onjob_titleChanging(value);
				this.SendPropertyChanging();
				this._job_title = value;
				this.SendPropertyChanged("job_title");
				this.Onjob_titleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_job_type", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string job_type
	{
		get
		{
			return this._job_type;
		}
		set
		{
			if ((this._job_type != value))
			{
				this.Onjob_typeChanging(value);
				this.SendPropertyChanging();
				this._job_type = value;
				this.SendPropertyChanged("job_type");
				this.Onjob_typeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_job_description", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string job_description
	{
		get
		{
			return this._job_description;
		}
		set
		{
			if ((this._job_description != value))
			{
				this.Onjob_descriptionChanging(value);
				this.SendPropertyChanging();
				this._job_description = value;
				this.SendPropertyChanged("job_description");
				this.Onjob_descriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_requirements", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string requirements
	{
		get
		{
			return this._requirements;
		}
		set
		{
			if ((this._requirements != value))
			{
				this.OnrequirementsChanging(value);
				this.SendPropertyChanging();
				this._requirements = value;
				this.SendPropertyChanged("requirements");
				this.OnrequirementsChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_publish_date", DbType="Date NOT NULL")]
	public System.DateTime publish_date
	{
		get
		{
			return this._publish_date;
		}
		set
		{
			if ((this._publish_date != value))
			{
				this.Onpublish_dateChanging(value);
				this.SendPropertyChanging();
				this._publish_date = value;
				this.SendPropertyChanged("publish_date");
				this.Onpublish_dateChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
