#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_69755_aspclass")]
public partial class feedbackDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void Insertfeedback(feedback instance);
  partial void Updatefeedback(feedback instance);
  partial void Deletefeedback(feedback instance);
  #endregion
	
	public feedbackDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DB_69755_aspclassConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public feedbackDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public feedbackDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public feedbackDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public feedbackDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<feedback> feedbacks
	{
		get
		{
			return this.GetTable<feedback>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.feedback")]
public partial class feedback : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _fb_Id;
	
	private string _fname;
	
	private string _email;
	
	private string _rdepartment;
	
	private string _title;
	
	private string _content;
	
	private string _section;
	
	private System.DateTime _feedbackDate;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onfb_IdChanging(int value);
    partial void Onfb_IdChanged();
    partial void OnfnameChanging(string value);
    partial void OnfnameChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnrdepartmentChanging(string value);
    partial void OnrdepartmentChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OncontentChanging(string value);
    partial void OncontentChanged();
    partial void OnsectionChanging(string value);
    partial void OnsectionChanged();
    partial void OnfeedbackDateChanging(System.DateTime value);
    partial void OnfeedbackDateChanged();
    #endregion
	
	public feedback()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fb_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int fb_Id
	{
		get
		{
			return this._fb_Id;
		}
		set
		{
			if ((this._fb_Id != value))
			{
				this.Onfb_IdChanging(value);
				this.SendPropertyChanging();
				this._fb_Id = value;
				this.SendPropertyChanged("fb_Id");
				this.Onfb_IdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fname", DbType="NVarChar(50)")]
	public string fname
	{
		get
		{
			return this._fname;
		}
		set
		{
			if ((this._fname != value))
			{
				this.OnfnameChanging(value);
				this.SendPropertyChanging();
				this._fname = value;
				this.SendPropertyChanged("fname");
				this.OnfnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string email
	{
		get
		{
			return this._email;
		}
		set
		{
			if ((this._email != value))
			{
				this.OnemailChanging(value);
				this.SendPropertyChanging();
				this._email = value;
				this.SendPropertyChanged("email");
				this.OnemailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rdepartment", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string rdepartment
	{
		get
		{
			return this._rdepartment;
		}
		set
		{
			if ((this._rdepartment != value))
			{
				this.OnrdepartmentChanging(value);
				this.SendPropertyChanging();
				this._rdepartment = value;
				this.SendPropertyChanged("rdepartment");
				this.OnrdepartmentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
	public string title
	{
		get
		{
			return this._title;
		}
		set
		{
			if ((this._title != value))
			{
				this.OntitleChanging(value);
				this.SendPropertyChanging();
				this._title = value;
				this.SendPropertyChanged("title");
				this.OntitleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_content", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string content
	{
		get
		{
			return this._content;
		}
		set
		{
			if ((this._content != value))
			{
				this.OncontentChanging(value);
				this.SendPropertyChanging();
				this._content = value;
				this.SendPropertyChanged("content");
				this.OncontentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_section", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string section
	{
		get
		{
			return this._section;
		}
		set
		{
			if ((this._section != value))
			{
				this.OnsectionChanging(value);
				this.SendPropertyChanging();
				this._section = value;
				this.SendPropertyChanged("section");
				this.OnsectionChanged();
			}
		}
	}

    [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_feedbackDate", DbType = "Date NOT NULL", IsDbGenerated = true)]
	public System.DateTime feedbackDate
	{
		get
		{
			return this._feedbackDate;
		}
		set
		{
			if ((this._feedbackDate != value))
			{
				this.OnfeedbackDateChanging(value);
				this.SendPropertyChanging();
				this._feedbackDate = value;
				this.SendPropertyChanged("feedbackDate");
				this.OnfeedbackDateChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
