#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DataSource")]
public partial class linqTbSubForumsDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void Inserttb_Sub_forums(tb_Sub_forums instance);
  partial void Updatetb_Sub_forums(tb_Sub_forums instance);
  partial void Deletetb_Sub_forums(tb_Sub_forums instance);
  #endregion
	
	public linqTbSubForumsDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DataSourceConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public linqTbSubForumsDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public linqTbSubForumsDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public linqTbSubForumsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public linqTbSubForumsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<tb_Sub_forums> tb_Sub_forums
	{
		get
		{
			return this.GetTable<tb_Sub_forums>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_Sub_forums")]
public partial class tb_Sub_forums : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private System.Nullable<int> _forumid;
	
	private System.Nullable<int> _styleid;
	
	private string _title;
	
	private string _contents;
	
	private System.Nullable<System.DateTime> _dates;
	
	private System.Nullable<System.Guid> _authorid;
	
	private System.Nullable<int> _first_forum;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnforumidChanging(System.Nullable<int> value);
    partial void OnforumidChanged();
    partial void OnstyleidChanging(System.Nullable<int> value);
    partial void OnstyleidChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OncontentsChanging(string value);
    partial void OncontentsChanged();
    partial void OndatesChanging(System.Nullable<System.DateTime> value);
    partial void OndatesChanged();
    partial void OnauthoridChanging(System.Nullable<System.Guid> value);
    partial void OnauthoridChanged();
    partial void Onfirst_forumChanging(System.Nullable<int> value);
    partial void Onfirst_forumChanged();
    #endregion
	
	public tb_Sub_forums()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_forumid", DbType="Int")]
	public System.Nullable<int> forumid
	{
		get
		{
			return this._forumid;
		}
		set
		{
			if ((this._forumid != value))
			{
				this.OnforumidChanging(value);
				this.SendPropertyChanging();
				this._forumid = value;
				this.SendPropertyChanged("forumid");
				this.OnforumidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_styleid", DbType="Int")]
	public System.Nullable<int> styleid
	{
		get
		{
			return this._styleid;
		}
		set
		{
			if ((this._styleid != value))
			{
				this.OnstyleidChanging(value);
				this.SendPropertyChanging();
				this._styleid = value;
				this.SendPropertyChanged("styleid");
				this.OnstyleidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(50)")]
	public string title
	{
		get
		{
			return this._title;
		}
		set
		{
			if ((this._title != value))
			{
				this.OntitleChanging(value);
				this.SendPropertyChanging();
				this._title = value;
				this.SendPropertyChanged("title");
				this.OntitleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contents", DbType="NVarChar(MAX)")]
	public string contents
	{
		get
		{
			return this._contents;
		}
		set
		{
			if ((this._contents != value))
			{
				this.OncontentsChanging(value);
				this.SendPropertyChanging();
				this._contents = value;
				this.SendPropertyChanged("contents");
				this.OncontentsChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dates", DbType="DateTime")]
	public System.Nullable<System.DateTime> dates
	{
		get
		{
			return this._dates;
		}
		set
		{
			if ((this._dates != value))
			{
				this.OndatesChanging(value);
				this.SendPropertyChanging();
				this._dates = value;
				this.SendPropertyChanged("dates");
				this.OndatesChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_authorid", DbType="UniqueIdentifier")]
	public System.Nullable<System.Guid> authorid
	{
		get
		{
			return this._authorid;
		}
		set
		{
			if ((this._authorid != value))
			{
				this.OnauthoridChanging(value);
				this.SendPropertyChanging();
				this._authorid = value;
				this.SendPropertyChanged("authorid");
				this.OnauthoridChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_first_forum", DbType="Int")]
	public System.Nullable<int> first_forum
	{
		get
		{
			return this._first_forum;
		}
		set
		{
			if ((this._first_forum != value))
			{
				this.Onfirst_forumChanging(value);
				this.SendPropertyChanging();
				this._first_forum = value;
				this.SendPropertyChanged("first_forum");
				this.Onfirst_forumChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
