#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Hospital")]
public partial class news_accordionDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void Insertaccordion_new(accordion_new instance);
  partial void Updateaccordion_new(accordion_new instance);
  partial void Deleteaccordion_new(accordion_new instance);
  #endregion
	
	public news_accordionDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DB_69755_aspclassConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public news_accordionDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public news_accordionDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public news_accordionDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public news_accordionDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<accordion_new> accordion_news
	{
		get
		{
			return this.GetTable<accordion_new>();
		}
	}
	
	public System.Data.Linq.Table<accordion_news_info> accordion_news_infos
	{
		get
		{
			return this.GetTable<accordion_news_info>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.accordion_news")]
public partial class accordion_new : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _an_id;
	
	private string _an_title;
	
	private System.DateTime _an_postedtime;
	
	private System.DateTime _an_lastupdate;
	
	private string _an_content;
	
	private System.Data.Linq.Binary _an_img;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onan_idChanging(int value);
    partial void Onan_idChanged();
    partial void Onan_titleChanging(string value);
    partial void Onan_titleChanged();
    partial void Onan_postedtimeChanging(System.DateTime value);
    partial void Onan_postedtimeChanged();
    partial void Onan_lastupdateChanging(System.DateTime value);
    partial void Onan_lastupdateChanged();
    partial void Onan_contentChanging(string value);
    partial void Onan_contentChanged();
    partial void Onan_imgChanging(System.Data.Linq.Binary value);
    partial void Onan_imgChanged();
    #endregion
	
	public accordion_new()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_an_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int an_id
	{
		get
		{
			return this._an_id;
		}
		set
		{
			if ((this._an_id != value))
			{
				this.Onan_idChanging(value);
				this.SendPropertyChanging();
				this._an_id = value;
				this.SendPropertyChanged("an_id");
				this.Onan_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_an_title", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
	public string an_title
	{
		get
		{
			return this._an_title;
		}
		set
		{
			if ((this._an_title != value))
			{
				this.Onan_titleChanging(value);
				this.SendPropertyChanging();
				this._an_title = value;
				this.SendPropertyChanged("an_title");
				this.Onan_titleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_an_postedtime", DbType="DateTime NOT NULL")]
	public System.DateTime an_postedtime
	{
		get
		{
			return this._an_postedtime;
		}
		set
		{
			if ((this._an_postedtime != value))
			{
				this.Onan_postedtimeChanging(value);
				this.SendPropertyChanging();
				this._an_postedtime = value;
				this.SendPropertyChanged("an_postedtime");
				this.Onan_postedtimeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_an_lastupdate", DbType="DateTime NOT NULL")]
	public System.DateTime an_lastupdate
	{
		get
		{
			return this._an_lastupdate;
		}
		set
		{
			if ((this._an_lastupdate != value))
			{
				this.Onan_lastupdateChanging(value);
				this.SendPropertyChanging();
				this._an_lastupdate = value;
				this.SendPropertyChanged("an_lastupdate");
				this.Onan_lastupdateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_an_content", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string an_content
	{
		get
		{
			return this._an_content;
		}
		set
		{
			if ((this._an_content != value))
			{
				this.Onan_contentChanging(value);
				this.SendPropertyChanging();
				this._an_content = value;
				this.SendPropertyChanged("an_content");
				this.Onan_contentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_an_img", DbType="Image", CanBeNull=true, UpdateCheck=UpdateCheck.Never)]
	public System.Data.Linq.Binary an_img
	{
		get
		{
			return this._an_img;
		}
		set
		{
			if ((this._an_img != value))
			{
				this.Onan_imgChanging(value);
				this.SendPropertyChanging();
				this._an_img = value;
				this.SendPropertyChanged("an_img");
				this.Onan_imgChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.accordion_news_info")]
public partial class accordion_news_info
{
	
	private int _an_id;
	
	private string _an_title;
	
	private System.DateTime _an_postedtime;
	
	private System.DateTime _an_lastupdate;
	
	private string _an_content;
	
	public accordion_news_info()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_an_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
	public int an_id
	{
		get
		{
			return this._an_id;
		}
		set
		{
			if ((this._an_id != value))
			{
				this._an_id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_an_title", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
	public string an_title
	{
		get
		{
			return this._an_title;
		}
		set
		{
			if ((this._an_title != value))
			{
				this._an_title = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_an_postedtime", DbType="DateTime NOT NULL")]
	public System.DateTime an_postedtime
	{
		get
		{
			return this._an_postedtime;
		}
		set
		{
			if ((this._an_postedtime != value))
			{
				this._an_postedtime = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_an_lastupdate", DbType="DateTime NOT NULL")]
	public System.DateTime an_lastupdate
	{
		get
		{
			return this._an_lastupdate;
		}
		set
		{
			if ((this._an_lastupdate != value))
			{
				this._an_lastupdate = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_an_content", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string an_content
	{
		get
		{
			return this._an_content;
		}
		set
		{
			if ((this._an_content != value))
			{
				this._an_content = value;
			}
		}
	}
}
#pragma warning restore 1591
