#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_69755_aspclass")]
public partial class rssfeedDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void Insertrss(rss instance);
  partial void Updaterss(rss instance);
  partial void Deleterss(rss instance);
  #endregion
	
	public rssfeedDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DB_69755_aspclassConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public rssfeedDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public rssfeedDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public rssfeedDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public rssfeedDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<rss> rsses
	{
		get
		{
			return this.GetTable<rss>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.rss")]
public partial class rss : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _rss_Id;
	
	private string _rss_title;
	
	private string _rss_url;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onrss_IdChanging(int value);
    partial void Onrss_IdChanged();
    partial void Onrss_titleChanging(string value);
    partial void Onrss_titleChanged();
    partial void Onrss_urlChanging(string value);
    partial void Onrss_urlChanged();
    #endregion
	
	public rss()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rss_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int rss_Id
	{
		get
		{
			return this._rss_Id;
		}
		set
		{
			if ((this._rss_Id != value))
			{
				this.Onrss_IdChanging(value);
				this.SendPropertyChanging();
				this._rss_Id = value;
				this.SendPropertyChanged("rss_Id");
				this.Onrss_IdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rss_title", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string rss_title
	{
		get
		{
			return this._rss_title;
		}
		set
		{
			if ((this._rss_title != value))
			{
				this.Onrss_titleChanging(value);
				this.SendPropertyChanging();
				this._rss_title = value;
				this.SendPropertyChanged("rss_title");
				this.Onrss_titleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rss_url", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string rss_url
	{
		get
		{
			return this._rss_url;
		}
		set
		{
			if ((this._rss_url != value))
			{
				this.Onrss_urlChanging(value);
				this.SendPropertyChanging();
				this._rss_url = value;
				this.SendPropertyChanged("rss_url");
				this.Onrss_urlChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
