<?xml version="1.0" encoding="utf-8"?><Database Name="DataSource" Class="tbforumsLinqDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=tcp:s10.winhost.com;Persist Security Info=True;User ID=DB_69755_aspclass_user" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DataSourceConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tb_forums" Member="tb_forums">
    <Type Name="tb_forums">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="dates" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="authorid" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="hf_nums" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="sfhf" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>